version: '3.3'

services:
  api:
    build: ./api
    restart: always
    ports:
      - '3000:3000'
    command: 'npm run dev'
    environment:
      - DB_HOST=db
      - DB_NAME=revisionist
      - DB_USER=postgres
      - DB_PASSWORD=password
      - MAILGUN_API_DOMAIN=sandboxcb7ded0b593148c8a7c8563c847612b0.mailgun.org
      - MAILGUN_API_KEY=key-39b373755c574d31004fbe6cd67418f8
      - HOSTNAME=http://localhost:3000
      - SENTRY_DSN=
      - SENTRY_ENVIRONMENT=dev
      - SENTRY_RELEASE=indev
      - NODE_ENV=
      - PORT=3000
    volumes:
      - ./api:/app/
      - /app/node_modules

  nginx:
    build: ./nginx
    ports:
      - '2000:2000'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /app/node_modules
    depends_on:
      - demo

  demo:
    build: ./demo
    ports:
      - '3000:3000'
    environment:
      - test_parameter=ping
    volumes:
      - ./demo:/app/
      - /app/node_modules

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=revisionist
    ports:
      - '5432:5432'
