export const UNIQUE_CONSTRAINT_ERROR = 'UNIQUE_CONSTRAINT_ERROR';
export const MALFORMED_JSON = 'MALFORMED_JSON';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const INVALID_METHOD = 'INVALID_METHOD';
export const VERIFICATION_TOKEN_NOT_FOUND = 'VERIFICATION_TOKEN_NOT_FOUND';
export const INVALID_VERIFICATION_TOKEN = 'INVALID_VERIFICATION_TOKEN';
